### ISSUE TITLE
Module __TunnelKitCore not found

### ISSUE THREAD

**Issue by SerhiiBychin** [passepartoutvpn/tunnelkit#132]
Can't import TunnelKit library into ObjC project.
I've added import a header like this in my ObjC class:

> #import "TunnelKit-Swift.h"

And when I try to compile project I stuck with the following error:

> Module '__TunnelKitCore' not found

Note: 'OpenVPN' class is visible in my ObjC class where I've added import. But can't compile project at all.

**Comment by keeshux** [comment]
Why would you want to use ObjC in 2019? Is it a legacy project? BTW I never tested nor meant to support the use of TunnelKit in ObjC projects, so let alone my response below, the issue will be closed.

I can still hint you at where to look at. Your problem is that TunnelKit has a "Core" module written in C/ObjC with that name, which I import into Swift code via a modulemap file. I don't know how you're importing TunnelKit into your project, but make sure to include the modulemap in the Swift module search path.

**Comment by pahnev** [comment]
You won't be able to use TunnelKit directly into ObjC class, as it's not really exposed for it.
If you can have Swift in your project, create a Swift class and import TunnelKit in that. You can then annotate your Swift class with `@objc`-marks and use TunnelKit in the ObjC.
