### ISSUE TITLE
Crash in OpenVPNSession.handleControlMessage(_:)

### ISSUE THREAD

**Issue by pahnev** [passepartoutvpn/tunnelkit#185]
# Summary
Every release we are getting some crashes from this function. No particular iOS or device version.
The Xcode's crash reporting doesn't show anything valuable, so perhaps it's the `fatalError` at the end of the function?

Latest app release had TunnelKit v.2.2.7 in it.

### Relevant logs and/or screenshots
![Screenshot 2020-11-20 at 14 06 21](https://user-images.githubusercontent.com/2078494/99798582-ecbef580-2b39-11eb-9076-ef9fd3339867.png)

**Comment by jurajhilje** [comment]
@pahnev I guess you are running the OpenVPN tunnel as a Network Extension? If yes, this is probably iOS system terminating the extension due to exceeding the 15MB memory limit. Try some memory/performance profiling to see whether this is the case.

**Comment by pahnev** [comment]
As Network Extension indeed. Is there some other way that I'm not aware of?

The problem is that even if I profile the memory usage, it probably won't reproduce the issue. We don't get thousands of these crashes, but one of the top crashers, as the app itself runs mostly in the background.

**Comment by keeshux** [comment]
The only `fatalError` comes from a nil `link?.remoteAddress`, which sounds a bit exaggerate of a reaction, but also unlikely.

You could try releasing a build without the assertion and see how it goes, still my feeling is that the extension would still crash in unpredictable ways. I've reported plenty of similar crashes which I haven't found a way to solve in years, and some threads on the Apple developer forum suggest that some of the issues may even come from internal Apple frameworks. I've never had particular user complaints since the only effect of these (rare) issues is a momentary disconnection.

OTOH, what's your app on the App Store?

**Comment by pahnev** [comment]
Yeah, I'd imagine that's it's not really affecting users, we have usually users reporting issues with IPSec. But just thought I'd write this down incase someone else is getting similar crash.

We're using TunnelKit in our [Freedome VPN](https://apps.apple.com/us/app/f-secure-freedome-vpn/id771791010) app.

**Comment by keeshux** [comment]
I can't find the source code of your app anywhere on the website. Are you aware that TunnelKit mandates that?

**Comment by pahnev** [comment]
We're aware of the license but feel free to contact our support or legal team. Don't know what's the email / most direct way, but I can get back to you with it on Monday.

**Comment by keeshux** [comment]
> We're aware of the license but feel free to contact our support or legal team. Don't know what's the email / most direct way, but I can get back to you with it on Monday.

Ah nice, you are aware i.e. deliberately infringing it.
